/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libCalculadora_JavaCalculadora */

#ifndef _Included_libCalculadora_JavaCalculadora
#define _Included_libCalculadora_JavaCalculadora
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libCalculadora_JavaCalculadora
 * Method:    sumar
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_libCalculadora_JavaCalculadora_sumar
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     libCalculadora_JavaCalculadora
 * Method:    restar
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_libCalculadora_JavaCalculadora_restar
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     libCalculadora_JavaCalculadora
 * Method:    multiplicar
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_libCalculadora_JavaCalculadora_multiplicar
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     libCalculadora_JavaCalculadora
 * Method:    dividir
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_libCalculadora_JavaCalculadora_dividir
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
